export const quote = [
  // direct quote / citation requests
  'quote',
  'quotes',
  'quotation',
  'line',
  'lines',
  'exact words',
  'exact wording',
  'verbatim',
  'word for word',
  'direct quote',
  'text says',
  'the book says',
  'the novel says',
  'the narrator says',

  // locating in the book
  'passage',
  'excerpt',
  'extract',
  'snippet',
  'section where',
  'part where',
  'chapter where',
  'page where',
  'in chapter',
  'in chapter ',
  'on page',
  'on page ',
  'at the end of',
  'at the beginning of',

  // “who said what” / dialogue
  'who said',
  'who says',
  'says to',
  'said to',
  'tell me what',
  'tells',
  'mentions',
  'asks',
  'replies',
  'responds',
  'states',

  // “find the scene” style
  'scene where',
  'moment when',
  'when does',
  'when did',
  'where does',
  'where did',
  'find where',
  'locate',
  'look up',
  'search for',
  'what chapter does',
  'what page does',

  // citations
  'cite',
  'citation',
  'reference',
  'provide a citation',
  'with citation',
  'with a page number',
  'page number',
];

export const quotePatterns: RegExp[] = [
  /\bwhat (page|chapter)\b/,
  /\b(page|chapter)\s+\d+\b/,
  /\bwhere (does|did)\b.*\b(say|mention|write|describe|happen)\b/,
  /\bwho (said|says|told|asks|asked)\b/,
  /\bexact (quote|words|wording)\b/,
  /\bquote(s)? (about|on|regarding)\b/,
  /\bcite\b|\bcitation\b/,
];